# Docker Compose for Church Member Management System
# 
# NOTE: This project now uses Supabase for the database.
# This file is kept for reference but is no longer needed.
#
# To set up the database:
# 1. Create a Supabase project at https://supabase.com
# 2. Follow the setup guide in setup-supabase.md
# 3. Run the SQL schema from database/init.sql in Supabase SQL Editor

# Uncomment below if you want to use local PostgreSQL instead of Supabase:
#
# version: '3.8'
# services:
#   postgres:
#     image: postgres:15
#     container_name: church-member-db
#     environment:
#       POSTGRES_DB: church_members
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#       - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
#     restart: unless-stopped
# 
# volumes:
#   postgres_data: